hello/accounts/urls.py
from django.urls import path
from.import views

app_name='accounts'
urlpatterns = [
     path('signup/',views.signup,name='signup'),
     path('log/',views.log,name='log'),
     path('logout/',views.log2,name='log2')
]

hello/arti/urls.py
#this is the second web app
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from . import views
app_name='arti'

urlpatterns=[
 path('arti/',views.arti,name="arti"),
 path('create/',views.create,name="create")
]

hello/hello/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
import re
from django.conf.urls.static import static
from django.conf import settings

app_name="hello"
urlpatterns = [
    path('',include('arti.urls')),
    path('admin/', admin.site.urls),
    path('about/',views.about,name='about'),
    path('main/',views.main,name='main'),
    path('accounts/',include('accounts.urls')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hello/accounts/models.py
from django.db import models

# Create your models here.

hello/arti/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Articles(models.Model):
      title=models.CharField(max_length=100)
      slug=models.SlugField()
      body=models.TextField()
      date=models.DateTimeField(auto_now_add=True)
      thumb=models.ImageField(default='default.png',blank=True)
      author=models.ForeignKey(User,default=None,   on_delete=models.CASCADE,)
def __str__(self):
    return self.title

def snippet(self):              #self pointed to the Article object
    return self.body[:50]+'....'# return only first 50 charcters and shows

hello/arti/forms.py
from django import forms
#for creating our own forms
from.import models
#from the current directory denoted by the dot
class CreateArticle(forms.ModelForm):
    class Meta:#which feild to be inherit m in meta should be in capital
       model=models.Articles
       fields=['title','body','slug','thumb']

hello/accounts/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
# Create your views here.

#function will fire when the user want to signup
def signup(request):
    if request.method=='POST':
       form=UserCreationForm(request.POST)
       if form.is_valid():
          user=form.save() #form.save return a user that we have saved in our database  
          login(request,user) 
          return redirect('arti:arti')
    else:  
       form=UserCreationForm()
    return render(request,'accounts/temp.html',{'form':form})

#function will fire when the user want to log in 
def log(request):
    if request.method=='POST':
       form=AuthenticationForm(data=request.POST)    
       if form.is_valid():
            user=form.get_user()  #take the user data filled in thr form and trasfer into the user
            login(request,user)  #retrieve
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('arti:arti')            
    else:
       form=AuthenticationForm()

    return render(request,'accounts/temp2.html',{'form':form})
# function will fire when the user want to logout
def log2(request):
    if request.method=='POST':
       logout(request)# do not need to specify which user need to be loged out because djanco know the current user to be loged out
       return redirect('arti:arti')

hello/arti/views.py
from django.shortcuts import render,redirect
# Create your views here.
from django.http import HttpResponse
from .models import Articles
from django.contrib.auth.decorators import login_required 
from .import forms

def arti(request):
    articles=Articles.objects.all().order_by('date')
    return render(request,'arti/arpit.html',{'article':articles})
def details(request,slug):
    return HttpResponse(slug)

#decorator add additional functionality to the funtion (here the decorator is the login_url)

@login_required(login_url="/accounts/log")
#this statement will prevent the user to not access the create funtion if the user is not logged in and the redirect the user to make login and redirect to the login page
def create(request):
    if request.method=='POST':
       form=forms.CreateArticle(request.POST,request.FILES) #when we uplooad the files they do not come with the request object but they come with the seperate object  files on the request object @request.FILES
       if form.is_valid():
          instance=form.save(commit=False) # here commit = false is doing an action which tells that dont instantly save the changes to the databse but wait we wanted to do something with the instance variable 
          instance.author=request.user#now we are saving the current user that is logined in the instance of the form attach the article with the user
          instance.save()# now saving the changes
          return redirect('arti:arti')
    else:
       form=forms.CreateArticle()
    return render(request,'arti/create.html',{'form':form})

hello/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render
def about(request):
    #return HttpResponse('about')
     return render(request,'par.html')
    #return HttpResponse('this is your first html rendering')
def main(request):
     return render(request,'new.html')

hello/accounts/templates/accounts/temp.html
{% extends 'base.html'%}
 {% block content %}
 <h2>you have now move to signup process igoigoghb</h2>
  <form class='form' action='/accounts/signup/' method="post">
  <!--must use the lower case letters in the method section-->
     {% csrf_token %}<!-- for authorization when we want to make a post request to the server from our site not from site of other and please accept this data and what we do send this token with our request-->
     {{form}}
     <input type="submit" value="submit">
  </form>
 {% endblock %}

hello/accounts/templates/accounts/temp2.html
{% extends 'base.html'%}
 {% block content %}
   <h1>you are now on the login page</h1> 
   <form class='site' action="{% url 'accounts:log' %}" method="post">
   <!--must use a single quote in the action and double quote in the method  -->
      {% csrf_token %}
       {{form}}
      {% if request.GET.next %}<!-- if next parameter is there in the url then we will redirect the user to create page-->
        <input type="hidden" name="next" value="{{request.GET.next}}">
   <!-- this 'value=""'-- will be sent as a post request to the log page-->
      {% endif %}
    <input type="submit" value="login">
   </form>
 {% endblock %}

hello/arti/templates/arti/arpit.html
{% load static %}
<html>
<head>
<title>hello</title>
</head>
 <link rel="stylesheet" href="{% static 'main2.css' %}" type="text/css" />

<body id="body">
<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
  <script src="{% static 'main2.js' %}"></script> <!-- This is how to include a static file -->
<meta name="viewport" content="width-device-width" initial-scale=1>
<header>
  <!-- <img class="image" src="Seabrook_Christian_School_logo.png" alt="logo"/>
   <div class="main"><h1>krishna school</h1></div>-->

<nav>
  <img src="{% static 'Seabrook_Christian_School_logo.png' %}" class="image22" />  
  <ul>
    <li><a href="{% url 'arti:create' %}">create article</a>
      <ul class="drop-menu menu-#{i}">
        <li>uno</li>
        <li>dos</li>
        <li>tres</li>
        <li>cuatro</li>
      </ul>
    </li>
    <li><a href="/about/">about</a>
      <ul class="drop-menu menu-#{i}">
        <li>uno</li>
        <li>dos</li>
        <li>tres</li>
      </ul>
    </li>
    <li>style 3
      <ul class="drop-menu menu-#{i}">
        <li>uno</li>
        <li>dos</li>
        <li>tres</li>
      </ul>
    </li>
    <li>style 4
      <ul class="drop-menu menu-#{i}">
        <li>uno</li>
        <li>dos</li>
        <li>tres</li>
      </ul>
    </li>
  </ul>
</nav>
  <dev class="name1">
     <img src="{% static 'the-archer-school-for-girls-p101217-2-520x250.jpg' %}" class="name2" alt="image"/>
  </div>
  <div class="articles" style="border:2px solid black;background-color:red;">
    {%for artic in article %}          <!-- syntax for writing the python code in it -->
       <div style="background-color:pink;">
         <h2><a href="http://www.google.com">{{artic.title}}</a></h2>
         <img src="{{ artic.thumb.url}}" height="200px" width="300px"/>
         <p>{{artic.body}}</p>
         <p>{{artic.date}}</p>
       </div>
    {% endfor%}
  </div>
  <!-- navigation buttons
   <button class="button" href="http://www.google.com">contact</button>
   <button class="button" href="http://www.google.com">About</button>
   <button class="button" href="http://www.google.com">Students</button>
   <button class="button" href="http://www.google.com">Home</button>
   <form id="form" action="arpi.html" method="POST" onsubmit="return checkinfo();">
      login Id:<input id="make1" type="text" name="login"/>
      password:<input id="make2" type="password" name="password"/>
      <input type="submit" value="submit"/>
   </form>
</div>
</header>-->
</header>
<!--
rotate buttons
<section>
      <div class="sec">
<div class="trigger">
  <div class="box"></div>
</div>
<div class="trigger">
<div class="box">
</div>
</div>
<div class="trigger">
<div class="box">
</div>
</div>
<div class="trigger">
<div class="box">
</div>
      </div>
 </div>
</section>-->
<div class="load"></div>
  <!--image slider
  <div>
     <img src="beautiful-wallpaper-39.jpg" id="image2"/>
  </div>-->
  <!--
   <div class="slidercontainer">
        <div class="showSlide">
            <img src="beautiful-wallpaper-39.jpg" />
            <div class="content">Slide1 heading</div>
        </div>
        <div class="showSlide">
            <img src="Screenshot from 2018-01-07 10-54-57.png" />
            <div class="content">Slide2 heading</div>
        </div>

        <div class="showSlide">
            <img src="Seabrook_Christian_School_logo.png" />
            <div class="content">Slide3 heading</div>
        </div>
        <div class="showSlide">
            <img src="IMG-20160507-WA0022.jpg" />
            <div class="content">Slide4 heading</div>
        </div>

        <a class="left" onclick="nextSlide(-1)">lmklinllk</a>
        <a class="right" onclick="nextSlide(1)">klnlknlkn</a>
    </div>-->

<!--<footer>
<div class="foot">
 <p>&copy; copyright to arpit varshney</p>
</div>
</footer>-->
</body>
</html>

hello/arti/templates/arti/create.html
{% extends 'base.html'%}

{%block content%}
   <div class="create">
    <h2>create a new awsome article</h2>
    <form class="site-form" action='/create/' method="post" enctype="multipart/form-data"> <!--now we sending our data to this url(arti(app name) create(name of the url)) via post request
this enctype is used here because we are uploading an image 
-->
          {%csrf_token%}
          {{form}}
        <input type="submit" value="create2">
     </form>
   </div>
   
{% endblock %}

hello/templates/base.html
<html>
<head>
 <title>new webpage</title>
</head>
<body style="background-color:light-blue;">
  <h1>this is my very first webpage</h1>
  <p>now i am going to talk little about this webpage in context without the reference of anyone and without the interference of everyone</p>
<nav>
   {%if user.is_authenticated %}<!--it will show the logout only when the user is authenticated-->
	<form class='select' action="{% url 'accounts:log2' %}" method="post"> 
	  <!-- whenever we want to sent the post request we need to add the csrf token for the security purposes-->
	   {%csrf_token%}
	   <button type="submit">logout</button>
	</form>
        <a href="{% url 'arti:create' %}">new article</a>
    {% else %}
        <a href="{% url 'accounts:log'%}">login</a>
        <a href="{% url 'accounts:signup'%}">signup</a>
    {% endif %}   
</nav>
{% block content %}
{% endblock %}
</body>
</html>

hello/templates/new.html
{% extends 'base.html'%}
 {% block content %}
 <h2>you are now on the second page</h2>
 {% endblock %}

hello/templates/par.html
{% load static from staticfiles %}
<html>
<head>
</head>
<body>
<link rel="stylesheet" href="{% static 'main.css' %}" type="text/css" />
 <script src="{% static 'main.js' %}"></script> <!-- This is how to include a static file -->
<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<div class="sky">
  <img src="{% static 'cloud1.jpeg' %}" class="cloud"/>
  <img src="{% static 'cloud1.jpeg' %}" class="cloud"/>
</div>
<div id="box1">
   <button class="button">burj khalifa</button>
</div>	
<section>
  <div class="main">
    <h2 id="h2" onclick="change();">burj khalifa</h2>
     <p>
        The Burj Khalifa (Arabic: برج خليفة‎, Arabic for "Khalifa Tower"; pronounced English: /ˈbɜːrdʒ kəˈliːfə/), known as the Burj Dubai before its inauguration, is a megatall skyscraper in Dubai, United Arab Emirates. With a total height of 829.8 m (2,722 ft) and a roof height (excluding antenna) of 828 m (2,717 ft), the Burj Khalifa has been the tallest structure in the world since its topping out in late 2008.[4][9]

Construction of the Burj Khalifa began in 2004, with the exterior completed five years later in 2009. The primary structure is reinforced concrete. The building was opened in 2010 as part of a new development called Downtown Dubai. It is designed to be the centrepiece of large-scale, mixed-use development. The decision to construct the building is reportedly based on the government's decision to diversify from an oil-based economy, and for Dubai to gain international recognition. The building was originally named Burj Dubai but was renamed in honour of the ruler of Abu Dhabi and president of the United Arab Emirates, Khalifa bin Zayed Al Nahyan;[3] Abu Dhabi and the UAE government lent Dubai money to pay its debts. The building broke numerous height records, including its designation as the tallest tower in the world.
     </p>
  </div>
</section>
</body>
</html